OWNERNAME  = 
OWNEREMAIL = 

all: build
build:
	YOURNAME="$(OWNERNAME)" YOUREMAIL="$(OWNEREMAIL)" /bin/bash ./bin/buildscript
clean:
	## Do not run make clean unless you really know what you are doing.
	## See the Makefile for details.
	## Note that running the rm command below will 
	## reset your package numbering to 1-1.
	## This is probably not what you want, so it is commented out. 
	## Enable at your own risk.
	# rm -rf ./packages
